config/routes.rb
Six470::Application.routes.draw do

  match "search/results" => "search#results", :as => :results

  match "search" => "search#search", :as => :search

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  resources :jobs
  
  match 'jobs/:id/json' => 'jobs#json'

  resources :users, :only => [] do
    resources :facebook_contacts, :only => [:index, :show]
  end

  get "home/home"
  
  root :to => "home#wrapper"
      
end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user
  
  validates_presence_of :query, :if => "location.blank?"
end

app/controllers/search_controller.rb
require 'indeed_scraper'

class SearchController < ApplicationController
  def search
    # Render a static-ish template with javascript to fetch the actual results
    @query = params[:q]
    @location = params[:l]
    @delayLoad = params[:delayLoad]
  end
  
  def results
    # Gets called by ajax, returns results as json
    @query = params[:q]
    @location = params[:l]
    
    search = Search.new
    search.query = @query
    search.location = @location
    search.user = current_user
    
    old_search = @recent_searches = Search.order('created_at DESC').first
    
    if search.query != old_search.query or search.location != old_search.location
      search.save
    end

    idsr = IndeedScraper.new
    api_results = idsr.search(@query, @location, '', 25)
    render :json => api_results    
  end
end

app/views/search/search.html.erb
<div id="header">
  <h1><a href="/">Jobography</a></h1>
  <span id="slogan">Work where you want to be</span>
</div>

<div id="map">
</div>

<div id="results_box">
  <h2><img alt='marker' style='position:relative;top:4px' src='/images/marker-red.png'>
    Results
  </h2>

  <a id="toggle_results_box" href="#"><img alt="collapse" src="/images/arrow-right1.png"></a>
  <div id="results_list">
    <ul id="results"></ul>
  </div>
</div>

<div id="toggle_contacts">
  <% if user_signed_in? %>
    <a id="toggle" href="#">Show contacts</a>
  <% else %>
    <%= link_to 'Show Contacts', new_user_registration_path, {:id => "sign_up"} %>
  <% end %>
</div>

<script>
var q = "<%= @query %>";
var l = "<%= @location %>";
var query_path = "<%= results_path %>";
var contacts_path = "/users/current/facebook_contacts";
var delayLoad = "<%= @delayLoad %>";
</script>

<%= javascript_include_tag 'search.js' %>

<%= javascript_include_tag 'http://maps.google.com/maps/api/js?sensor=false&callback=loadMap' %>

<div id="search_again">
</div>

<div id="indeed_logo">
  <a target="indeed" href="http://www.indeed.com">Jobs by<br/>
    <img alt='Indeed' src='/images/indeed.gif'></a>
</div>