config/routes.rb
Six470::Application.routes.draw do

  match "search/results" => "search#results", :as => :results

  match "search" => "search#search", :as => :search

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  resources :jobs
  
  match 'jobs/:id/json' => 'jobs#json'

  resources :users, :only => [] do
    resources :facebook_contacts, :only => [:index, :show]
  end

  get "home/home"
  
  root :to => "home#wrapper"
      
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    @recent_searches = Search.order('created_at DESC').limit(2)
  end
  
  def wrapper
    render :layout => false
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def recent_search_link(search)
    q = search.query
    l = search.location
    
    qs = URI::escape q
    ls = URI::escape l
    
    link = "<a class=recent href=#{search_path}?q=#{qs}" +
    "&l=#{ls} data-q='#{qs}' data-l='#{ls}'>"
    
    if search.query != '' and search.location != ''
      link + "#{h q} near #{h l}</a>?"
    elsif (search.query != '')
      link + "#{h q}</a> jobs?"
    else
      "jobs near " + link + "#{h l}</a>?"
    end
  end
end

app/views/home/home.html.erb
<div id="logo">
<h1>Jobography</h1>
</div>

<div id="inputform">
<%= form_tag search_path, :method => "get" do %>
  Find me a 
  <%= text_field_tag :q, "", {:placeholder => "what"} %> job near
  <%= text_field_tag :l, "", {:placeholder => "where (optional)"} %>
  <%= submit_tag "go!", {:class => "button"} %><br /> 
<% end %>
</div>

<% if @recent_searches.length >= 2 %>
  <div id="recent">
    <p>Recent searches:</p>
    <p>How about <%= raw recent_search_link(@recent_searches[0]) %></p>
    <p>Or maybe <%= raw recent_search_link(@recent_searches[1])%></p>
  </div>
<% end %>

<div id="infotext">
  Find out where all the jobs you want are. &nbsp;<%= link_to 'Link your Facebook', new_user_registration_path, {:id => "sign_up"} %> account and see where your contacts have worked. &nbsp;Use your social networks to choose the best place for you to get a job. 
<p>Jobography helps you <strong>work where you want to be.</strong></p>
</div>

app/views/home/welcome.html.erb
<br/><br/>

<div id="map" style="width:750px; height:500px; margin:auto" > </div>

<script type="text/javascript">
  function loadKonami() {
    konami = new Konami();
    konami.code = function() {
      var greeting = document.getElementById("greeting");
      greeting.innerHTML = "Greetings, human!";
    
      /* Inject cornify (www.cornify.com), code lifted from their bookmarklet */
      var cornify_div = document.createElement('div');
      cornify_div.id = '__cornify_nodes';
      document.body.appendChild(cornify_div);
    
      var scrpt = document.createElement('script');
      scrpt.src = 'http://cornify.com/js/cornify.js';
      scrpt.onload = function() { cornify_add(); }
    
      cornify_div.appendChild(scrpt);
    }
    konami.load();
  }

  function loadmap() {
    var center = new google.maps.LatLng(39.109, -94.589);

    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        center = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
        map.setCenter(center);
      }, function() {});
    }
    
    var options = {
      zoom: 4,
      center: center,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      panControl: true,
      mapTypeControl: false,
      streetViewControl: true
    };
    
    var map = new google.maps.Map(document.getElementById("map"), options);
    
    var joburl = '<%= jobs_url %>/';
    
    for (var i = 510; i < 520; i++) {
      $.getJSON(joburl+i+'/json', function(data) {
        var marker = new google.maps.Marker({
          map: map,
          animation: google.maps.Animation.DROP,
          position: new google.maps.LatLng(data.job.lat, data.job.long),
          title: data.job.title + ' - ' + data.job.company
        });
      });
    }
  }
</script>

<%= javascript_include_tag 'http://maps.google.com/maps/api/js?sensor=false&callback=loadmap' %>
<%= javascript_include_tag 'konami.js', :onload => 'loadKonami()' %>

app/views/home/wrapper.html.erb
<!DOCTYPE html>
<head>
<title>Jobography</title>

<script>
if (window != window.top) { // In frame, need to break out
  parent.window.location.reload(true);
}
</script>

<%= stylesheet_link_tag 'wrapper.css' %>
<%= stylesheet_link_tag 'default.css' %>
<%= stylesheet_link_tag 'home.css' %>

<%= javascript_include_tag 'jquery.min.js' %>
<%= javascript_include_tag 'urlEncode.js' %>
<%= javascript_include_tag 'wrapper.js' %>

<%= csrf_meta_tag %>
</head>

<body>

<div id="window">
  <div id="logintab">
     <% if user_signed_in? %>
       Hello, &nbsp;<%= current_user.name %> &nbsp; | &nbsp;
       <%= link_to 'Edit account', edit_user_registration_path, {:id => "edit_account" }%>
       &nbsp; | &nbsp; <%= link_to 'Log out', destroy_user_session_path, {:id => "sign_out"} %>
     <% else %>
       <%= link_to 'Sign in', new_user_session_path, {:id => "sign_in"} %> |
       <%= link_to 'Sign up', new_user_registration_path, {:id => "sign_up"} %>
     <% end %>
   </div>
  
  <div id='frame'>
    <% unless current_user %>
      <iframe id='login' src='/users/sign_in'></iframe>
      <iframe id='signup' src='/users/sign_up'></iframe>
    <% end %>
    
    <iframe id='home' src='/home/home'></iframe>
    <iframe id='map' src='/search?delayLoad=true'></iframe>

  </div>
  
  <div id="footer">
    <a href="mailto:jobography@mit.edu?Subject=Jobography%20Feedback">Contact us!</a>
  </div>
</div>

</body>
</html>